package com.ecoprocure.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;

@Entity
@Table(name = "employee")
public class Employee {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "employee_id")
    private Integer employeeId;//Integer: because the ID is generated by the database and is null before insertion.
    @Column(name = "employee_name")
    @NotBlank(message="Employee name Cannot be empty")//validation
    @Size(min= 3, max =50, message="Employee must be between 3 and 50 characters")//validation
    private String employeeName;
    @Column(name = "email")
    @NotBlank(message = "Email cannot be empty")
    @Email(message = "Enter a valid email address")
    private String email;
    @Column(name = "password")
    @NotBlank(message = "Password cannot be empty")
    @Size(min = 6, message = "Password must contain at least 6 characters")
    private String password;
    @Column(name = "phone_number")
    @NotBlank(message = "Phone number cannot be empty")
    @Pattern(regexp = "^[0-9]{10}$", message = "Phone number must contain exactly 10 digits")
    private String phoneNumber;
    @Column(name = "department")
    @NotBlank(message = "Department cannot be empty")
    private String department;
    @Column(name = "role")
    @NotBlank(message = "Role cannot be empty")
    private String role;

     public Employee(){

    }//default constructor because it creates obj automatically when fetching data from the database

    public Employee(Integer employeeId, String employeeName,String email, String password,String phoneNumber, String department, String role){
        this. employeeId=employeeId;
        this.employeeName=employeeName;
        this.email=email;
        this.password=password;
        this.phoneNumber=phoneNumber;
        this.department=department;
        this.role=role;
    }



    public Integer getEmployeeId() {
    return employeeId;
    }

    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    public String getEmployeeName() {
        return employeeName;
    }

    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    //I overrode toString() so that whenever an Employee object is printed, it displays meaningful employee details instead of the default object reference.
    @Override
public String toString() {
    return "Employee{" +
            "employeeId=" + employeeId +
            ", employeeName='" + employeeName + '\'' +
            ", email='" + email + '\'' +
            ", password='" + password + '\'' +
            ", phoneNumber='" + phoneNumber + '\'' +
            ", department='" + department + '\'' +
            ", role='" + role + '\'' +
            '}';
}

   
}
